# Generated by Django 4.1.3 on 2023-01-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_baza_ogloszen_delete_ogloszenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baza_ogloszen',
            name='data_zakonczenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
